title: Selman Waksman - An Impact on Microbiology 
description: A hub for Selman Waksman! Created by Samiha Nasrin for Microbiology with Dr.Mahmoud. 
baseurl: "/"
url: "https://selmanwaksman.microbiology.com"

back_to_top: true
back_to_top_text: "Back to top" 

aux_links:
"Nobel Piece Prize": 
  - "https://www.nobelprize.org/prizes/medicine/1952/summary/" 
"My Life with Microbes" 
  - "https://archive.org/details/in.ernet.dli.2015.271350/page/n221/mode/2up?view=theater" 

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

color_scheme: dark

remote_theme: pmarsceill/just-the-docs
